language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"
install:
  - npm install
  - npm install twitter2pg
script:
  - git clone https://github.com/rrwen/twitter2pg
  - cd twitter2pg
  - npm install
  - npm update --dev
