language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE postgres;' -U postgres  
install:
  - npm install
script:
  - npm run docs
  - npm test
after_success:
  - npm run coverage
